#docker compose

version: "3.7"
services:
  mongodb:
    image: mongo:4.2.8
    container_name: mongo_server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
